function safe(value, fallback = '') {
  return String(value ?? fallback)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;')
}

function money(value) {
  return `BDT ${Number(value || 0).toLocaleString('en-BD')}`
}

export function openInvoicePdf(order, store = {}) {
  if (!order) return
  const items = Array.isArray(order.items) ? order.items : []
  const orderDate = order.created_at
    ? new Date(order.created_at).toLocaleDateString('en-BD', { day: 'numeric', month: 'long', year: 'numeric' })
    : new Date().toLocaleDateString('en-BD')
  const subtotal = items.reduce((sum, item) => sum + Number(item.price || 0) * Number(item.qty || item.quantity || 1), 0)
  const delivery = Math.max(0, Number(order.total || 0) - subtotal)
  const html = `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Invoice ${safe(order.order_id || order.id)}</title>
  <style>
    *{box-sizing:border-box} body{font-family:Inter,Arial,sans-serif;margin:0;background:#f8fafc;color:#0f172a;padding:32px}
    .page{max-width:820px;margin:0 auto;background:white;border-radius:24px;padding:36px;box-shadow:0 20px 50px rgba(15,23,42,.08)}
    .top{display:flex;justify-content:space-between;gap:24px;border-bottom:2px solid #eef2ff;padding-bottom:24px}
    .brand{font-size:26px;font-weight:900;letter-spacing:-.04em}.brand span{color:#4f46e5}.muted{color:#64748b;font-size:13px;line-height:1.6}
    .invoice-title{text-align:right}.invoice-title h1{margin:0;font-size:30px;letter-spacing:-.04em}.pill{display:inline-flex;margin-top:8px;border-radius:999px;background:#eef2ff;color:#3730a3;padding:6px 12px;font-size:12px;font-weight:800;text-transform:uppercase}
    .grid{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin:28px 0}.box{border:1px solid #e2e8f0;border-radius:18px;padding:18px;background:#f8fafc}.box h3{margin:0 0 10px;font-size:12px;text-transform:uppercase;letter-spacing:.12em;color:#64748b}.box p{margin:4px 0;font-size:14px}
    table{width:100%;border-collapse:collapse;margin-top:24px}th{text-align:left;background:#f8fafc;color:#64748b;text-transform:uppercase;letter-spacing:.1em;font-size:11px;padding:12px}td{padding:14px 12px;border-bottom:1px solid #e2e8f0;font-size:14px}.right{text-align:right}.totals{margin-left:auto;margin-top:24px;max-width:320px}.totals div{display:flex;justify-content:space-between;padding:8px 0;color:#475569}.totals .grand{font-size:20px;font-weight:900;color:#0f172a;border-top:2px solid #e2e8f0;padding-top:14px;margin-top:8px}
    .footer{margin-top:34px;border-top:1px solid #e2e8f0;padding-top:18px;text-align:center;color:#64748b;font-size:12px}
    @media print{body{background:white;padding:0}.page{box-shadow:none;border-radius:0}.no-print{display:none}}
  </style>
</head>
<body>
  <div class="page">
    <div class="top">
      <div>
        <div class="brand">Bazar<span>HQ</span></div>
        <p class="muted"><strong>${safe(store.shop_name || order.store_name || 'Shop')}</strong><br>${safe(store.subdomain || '')}</p>
      </div>
      <div class="invoice-title">
        <h1>Invoice</h1>
        <div class="muted">${safe(order.order_id || order.id)}<br>${safe(orderDate)}</div>
        <span class="pill">${safe(order.status || 'pending')}</span>
      </div>
    </div>

    <div class="grid">
      <div class="box"><h3>Customer</h3><p><strong>${safe(order.customer_name)}</strong></p><p>${safe(order.customer_phone)}</p><p>${safe(order.customer_email)}</p></div>
      <div class="box"><h3>Delivery</h3><p>${safe(order.delivery_address || order.address)}</p><p>${safe(order.district)}</p><p>${safe(order.delivery_note || order.note)}</p></div>
    </div>

    <table>
      <thead><tr><th>Item</th><th>Variant</th><th class="right">Qty</th><th class="right">Price</th><th class="right">Total</th></tr></thead>
      <tbody>
        ${items.map(item => {
          const qty = Number(item.qty || item.quantity || 1)
          const price = Number(item.price || 0)
          return `<tr><td><strong>${safe(item.title || item.name)}</strong></td><td>${safe(item.variant_label || item.variant || '—')}</td><td class="right">${qty}</td><td class="right">${money(price)}</td><td class="right">${money(price * qty)}</td></tr>`
        }).join('')}
      </tbody>
    </table>

    <div class="totals">
      <div><span>Subtotal</span><strong>${money(subtotal)}</strong></div>
      <div><span>Delivery</span><strong>${money(delivery)}</strong></div>
      <div><span>Payment</span><strong>${safe(order.payment_method || '—').toUpperCase()}</strong></div>
      <div class="grand"><span>Total</span><span>${money(order.total)}</span></div>
    </div>

    <div class="footer">Thank you for shopping with ${safe(store.shop_name || 'this store')}. Invoice generated by BazarHQ.</div>
  </div>
  <script>window.onload=()=>setTimeout(()=>window.print(),250)</script>
</body>
</html>`
  const win = window.open('', '_blank', 'noopener,noreferrer,width=920,height=900')
  if (!win) return
  win.document.open()
  win.document.write(html)
  win.document.close()
}
