-- =============================================================================
-- BazarHQ OPTIONAL SUPER ADMIN SEED TEMPLATE
-- =============================================================================
-- Do not put a real password or TOTP secret in Git.
-- The current production flow expects the password hash format generated by the
-- Super Admin setup/backend implementation. Create the hash through that trusted
-- setup path, then run an INSERT like the commented template below.
-- =============================================================================

/*
insert into public.admin_users(
  email,
  password_hash,
  role,
  is_active,
  totp_enabled,
  failed_attempts,
  locked_until
)
values(
  lower('admin@example.com'),
  '<HASH_GENERATED_BY_THE_ADMIN_SETUP_FLOW>',
  'full_access',
  true,
  false,
  0,
  null
)
on conflict((lower(email))) do update set
  password_hash=excluded.password_hash,
  role=excluded.role,
  is_active=true,
  failed_attempts=0,
  locked_until=null,
  updated_at=now();
*/
